# tinyrocket_config.yaml
format: naja_if
input_paths:
  - tinyrocket_naja.if
  - tinyrocket_naja_edited.if
liberty_files:
  - NangateOpenCellLibrary_typical.lib
  - fakeram45_1024x32.lib
  - fakeram45_64x32.lib
log_level: info

